[package]
name = "blockworld-client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { package = "blockworld-common", path = "../common" }
glam = "0.29"
env_logger = "0.10"
log = "0.4"
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["serde"] }
