[package]
name = "blockworld-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
fastrand = "2.3.0"
glam = { version = "0.29", features = ["serde"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
ron = "0.10.1"
noise = "0.9"
